config/routes.rb
Rails.application.routes.draw do
  resources :quizzes do    
    resources :questions, only: [:new, :destroy] do
      resources :answers, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  get 'quizzes/:share_token/public', to: 'quizzes#public_show', as: :public_quiz
  post 'quizzes/:share_token/submit_answer', to: 'answers#public_create', as: :public_quiz_answers

  # get 'quizzes/:share_token/thank_you', to: 'quizzes#thank_you', as: 'thank_you_quiz'
  
  resources :answers, only: [:create]

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "quizzes#index"

  # root to: redirect('/quizzes')
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers, inverse_of: :question, dependent: :destroy
  
  validates :name, presence: true

  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: ->(attributes) { attributes['content'].blank? }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @quiz = Quiz.find(params[:quiz_id])
    @question = @quiz.questions.build
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    # @question.destroy!

    # respond_to do |format|
    #   format.html { redirect_to questions_path, notice: "Question was successfully destroyed.", status: :see_other }
    #   format.json { head :no_content }

    question = Question.find(params[:id])
    question.destroy
  rescue ActiveRecord::RecordNotFound
    question = Task.new(id: params[:id])
  ensure
    respond_to do |format|
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.expect(question: [ :quiz_id, :content ])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quiz_id, style: "display: block" %>
    <%= form.text_field :quiz_id %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<%= fields_for [@question.quiz, @question] do |ff| %>
  <fieldset id="<%= dom_id(question) %>">
    <legend>Question info</legend>
    <%= ff.text_field :name %><br>
    <%= ff.text_field :content %>
    <%= ff.hidden_field :id %>
    <%= button_tag "Remove question", formaction: question_path(dom_id(question)), formmethod: :delete %>
  </fieldset>
<% end %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question.id %>

app/views/questions/edit.html.erb
<% content_for :title, "Editing question" %>

<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Questions" %>

<h1>Questions</h1>

<div id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
    <p>
      <%= link_to "Show this question", question %>
    </p>
  <% end %>
</div>

<%= link_to "New question", new_question_path %>

app/views/questions/new.html.erb
<% content_for :title, "New question" %>

<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/new.turbo_stream.erb
<%= turbo_stream.append :questions do %>
  <%= render partial: "questions/question", locals: { question: @question } %>
<% end %>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>