config/routes.rb
Rails.application.routes.draw do
  resources :quizzes do    
    resources :questions, only: [:new, :destroy] do
      resources :answers, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  get 'quizzes/:share_token/public', to: 'quizzes#public_show', as: :public_quiz
  post 'quizzes/:share_token/submit_answer', to: 'answers#public_create', as: :public_quiz_answers

  # get 'quizzes/:share_token/thank_you', to: 'quizzes#thank_you', as: 'thank_you_quiz'
  
  resources :answers, only: [:create]

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "quizzes#index"

  # root to: redirect('/quizzes')
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, except: [:public_show]
  before_action :set_quiz, only: %i[ show edit update destroy ]
  # skip user authentication for take action if you want guests to take quiz

  def public_show
    @quiz = Quiz.find_by!(share_token: params[:share_token])
    @questions = @quiz.questions.includes(:answers)
    @answer = Answer.new
  end

  def take
    @quiz = Quiz.find(params[:id])
    # show quiz questions to user here
  end

  def submit
    @quiz = Quiz.find(params[:id])
    # process answers from params and save a Response record
    # optionally associate with current_user if logged in
  end

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = current_user.quizzes
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = current_user.quizzes.build
    10.times do
      question = @quiz.questions.build
      question.answers.build
    end
  end

  # GET /quizzes/1/edit
  def edit
    (10 - @quiz.questions.size).times do
      question = @quiz.questions.build
      # question.answers.build
    end
  end

  # POST /quizzes or /quizzes.json
  def create
    # Quiz.new(quiz_params)
    @quiz = current_user.quizzes.build(quiz_params)
    if @quiz.save
      redirect_to @quiz, notice: "Quiz was successfully created."
    else
      render :new
    end

    # respond_to do |format|
    #   if @quiz.save
    #     format.html { redirect_to @quiz, notice: "Quiz was successfully created." }
    #     format.json { render :show, status: :created, location: @quiz }
    #   else
    #       format.html { render :new, status: :unprocessable_entity }
    #       format.json { render json: @quiz.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    # if @quiz.update(quiz_params)
    #   redirect_to @quiz, notice: 'Quiz was successfully updated.'
    # else
    #   render :edit
    # end

    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: "Quiz was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy!

    respond_to do |format|
      format.html { redirect_to quizzes_path, notice: "Quiz was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = current_user.quizzes.find(params[:id])
      # Quiz.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      # params.expect(quiz: [ :title, :description ])
      params.require(:quiz).permit(
        :title, :description,
        questions_attributes: [
        :id, :name, :_destroy,
        answers_attributes: [:id, :content, :_destroy]
        ]
      )
    end

    def thank_you
      @quiz = Quiz.find_by!(share_token: params[:share_token])
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |f| %>
  <div class="mb-3">
    <strong><%= f.label :title, class: "form-label" %></strong>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3 border-bottom border-primary pb-4">
    <strong><%= f.label :description, class: "form-label" %></strong>
    <%= f.text_area :description, class: "form-control", rows: 3 %>
  </div>

  <h2 class="mb-3">Questions</h2>

  <%= f.fields_for :questions do |qf| %>
    <% question_index = qf.index + 1 %>
    <div class="mb-3">
      <label class="form-label">
        <strong>Question <%= question_index %>:</strong>
      </label>
      <%= qf.text_area :name, class: "form-control", rows: 2 %>
    </div>
  <% end %>
  
  <%= f.submit "Save", class: "btn btn-success w-100" %>
<% end %>

app/views/quizzes/_question_fields.html.erb
<div class="nested-fields">
  <%= f.label :name, "Question Title" %><br>
  <%= f.text_field :name %><br>

  <%= f.label :content, "Question Content" %><br>
  <%= f.text_area :content %><br>

  <% if f.object.persisted? %>
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, "Remove question" %>
  <% else %>
    <button type="button" class="remove-question">Remove question</button>
  <% end %>

  <hr>
</div>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>" class="list-group-item d-flex justify-content-between lh-sm">
  <div style="margin-left: 20px">
    <p>
      <strong>Title:</strong>
      <%= quiz.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= quiz.description %>
    </p>
  </div>
</div>

<div class="card-header py-3 bg-transparent border-primary"></div>

<% quiz.questions.each_with_index do |question, index| %>
  <div class="card-body">
    <strong>Question <%= index + 1 %>:</strong> <%= question.name %>
    <% if question.answers.any? %>
      <table class="table table-striped">
        <% question.answers.each do |answer| %>
          <tr>
            <td style="padding: 5px; width: 20%;">
              <%= answer.participant_initials || "guest" %>
            </td>
            <td style="padding: 5px; width: 30%;">
              <%= answer.participant_email || "guest" %>
            </td>
            <td style="padding: 5px;">
              <%= answer.content %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p style="margin-left: 20px; color: gray;">No answers yet.</p>
    <% end %>
  </div>
<% end %>

app/views/quizzes/_quiz_row.html.erb
<tr id="<%= dom_id quiz %>">
  <td>
    <button type="button" class="btn btn-link"><%= link_to quiz %></button>
  </td>
  <td class="fw-medium align-middle"><%= quiz.description %></td>
  <td>
    <div style="display: flex; gap: 5px;">
      <%= button_to 'Edit', edit_quiz_path(quiz), method: :get, type: "button", class: "btn btn-info" %>
      <%= button_to 'Delete', quiz, method: :delete, type: "button", class: "btn btn-danger"%>
    </div>
  </td>
  <td><%= link_to public_quiz_url(quiz.share_token), public_quiz_url(quiz.share_token), target: "_blank", class: "btn btn-link" %></td>
</tr>

app/views/quizzes/edit.html.erb
<%= form_with(model: @quiz, local: true) do |f| %>
  <div class="card mb-4 rounded-3 shadow-sm border-primary">
    <!-- Card header -->
    <div class="card-header py-3 text-bg-primary border-primary">
      <div class="d-flex justify-content-between align-items-center">
        <!-- Left side -->
        <h3 class="my-0 fw-normal">Questionare editor</h3>

        <!-- Right side buttons -->
        <div class="btn-group">
          <%= f.submit "Save", class: "btn btn-outline-light" %>
          <%= link_to "Results", @quiz, class: "btn btn-outline-info" %>
          <%= link_to "Home", quizzes_path, class: "btn btn-outline-warning" %>
        </div>
      </div>
    </div>

    <!-- Card body -->
    <div class="card-body">
      <%= render "form", quiz: @quiz %>

      <hr>
      <p class="mb-0">
        <strong>Share public link:</strong><br>
        <%= public_quiz_url(share_token: @quiz.share_token) %>
      </p>
    </div>
  </div>
<% end %>

app/views/quizzes/index.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <h2 class="fs-2">Questionares</h2>
  <br>

  <div class="bd-example">
    <table class="table table-hover" id="quizzes">
      <thead>
        <tr>
          <th class="text-start fw-bold">Title</th>
          <th class="text-start fw-bold">Description</th>
          <th class="text-start fw-bold">Actions</th>
          <th class="text-start fw-bold">Take questionare/Share</th>
        </tr>
      </thead>
      <tbody>
        <% @quizzes.each do |quiz| %>
          <%= render 'quiz_row', quiz: quiz %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="d-grid gap-2">
    <%= link_to "Create a new Questionare", new_quiz_path, class: "btn btn-success" %>
  </div>
</div>

app/views/quizzes/new.html.erb
<% content_for :title, "New quiz" %>

<%= form_with(model: @quiz, local: true) do |f| %>
  <div class="card mb-4 rounded-3 shadow-sm border-primary">
    <!-- Card header -->
    <div class="card-header py-3 text-bg-primary border-primary">
      <div class="d-flex justify-content-between align-items-center">
        <!-- Left side -->
        <h3 class="my-0 fw-normal">New Questionare</h3>

        <!-- Right side buttons (optional for New) -->
        <div class="btn-group">
            <%= f.submit "Save", class: "btn btn-outline-light" %>
            <%= link_to "Home", quizzes_path, class: "btn btn-outline-warning" %>
          </div>
      </div>
    </div>

    <!-- Card body -->
    <div class="card-body">
      <%= render "form", quiz: @quiz %>
    </div>
  </div>
<% end %>

app/views/quizzes/public_show.html.erb
<h1 class="mb-4"><%= @quiz.title %></h1>

<% if flash[:notice] %>
  <p class="text-success"><%= flash[:notice] %></p>
  
<% else %>
  <%= form_with url: public_quiz_answers_path(@quiz.share_token), local: true do |f| %>
    <div class="card mb-4 rounded-3 shadow-sm border-primary">
      <!-- Card header -->
      <div class="card-header py-3 text-bg-primary border-primary">
        <div class="d-flex justify-content-between align-items-center">
          <!-- Left side -->
          <h3 class="my-0 fw-normal">Submit Your Answers</h3>

          <!-- Right side buttons -->
          <div class="btn-group">
            <% if user_signed_in? %>
              <%= link_to "Home", quizzes_path, class: "btn btn-outline-warning" %>
            <% else %>
              <%= link_to 'Log in', new_user_session_path, class: "btn btn-outline-info" %>
              <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-info" %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Card body -->
      <div class="card-body">
        <% if !user_signed_in? %>
          <div class="mb-3">
            <%= label_tag :participant_initials, "Initials", class: "form-label fw-bold" %>
            <%= text_field_tag :participant_initials, nil, placeholder: "Enter your initials", class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= label_tag :participant_email, "Email", class: "form-label fw-bold" %>
            <%= email_field_tag :participant_email, nil, placeholder: "Enter your email", class: "form-control" %>
          </div>
        <% else %>
          <p><strong>Initials:</strong> <%= current_user.username %></p>
          <p><strong>Email:</strong> <%= current_user.email %></p>
        <% end %>

        <% @quiz.questions.each_with_index do |question, idx| %>
          <div class="mb-3">
            <label class="form-label fw-bold">Question <%= idx + 1 %>: <%= question.name %></label>
            <%= text_area_tag "answers[#{question.id}]", nil, placeholder: "Your answer...", class: "form-control", rows: 3 %>
          </div>
        <% end %>

        <div class="mt-4">
          <%= f.submit "Submit all answers", class: "btn btn-success w-100" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/quizzes/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="card mb-4 rounded-3 shadow-sm border-primary">
  <div class="card-header py-3 text-bg-primary border-primary">
    <div class="d-flex justify-content-between align-items-center">
      <!-- Left side -->
      <h3 class="my-0 fw-normal">Questionare results</h3>

      <!-- Right side buttons -->
      <div class="btn-group">
        <%= link_to "Edit", edit_quiz_path(@quiz), class: "btn btn-outline-info" %>
        <%= button_to "Delete", @quiz, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        <%= link_to "Home", quizzes_path, class: "btn btn-outline-warning" %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <%= render "quiz", quiz: @quiz %>
  </div>
</div>

<!-- Action buttons at bottom
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center pb-3 mb-3">
      <li><%= link_to "Edit this Questionare", edit_quiz_path(@quiz), class: "nav-link px-2 text-body-secondary nav-item" %></li>
      <li><%= link_to "Back to Library", quizzes_path, class: "nav-link px-2 text-body-secondary nav-item" %></li>
      <li><%= button_to "Delete this Questionare", @quiz, method: :delete, data: { confirm: "Are you sure?" }, class: "nav-link px-2 text-body-secondary nav-item" %></li>
    </ul>
  </footer>
</div> -->